export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import LegalPage from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Privacy Policy for iBudget.au, explaining how personal information, calculator data, analytics, saved calculations, cookies and advertising data are handled.",
};

const sections = [
  {
    heading: "1. About this policy",
    paragraphs: [
      "This Privacy Policy explains how iBudget.au collects, uses, stores and shares information when you use this website. iBudget is an Australian financial calculator website designed to let users access calculators without creating a public account.",
      "This policy is written with the Australian Privacy Principles under the Privacy Act 1988 (Cth) in mind. Even where a small business exemption may apply, iBudget aims to follow practical privacy standards and to clearly explain how information is handled.",
    ],
  },
  {
    heading: "2. Using iBudget anonymously",
    paragraphs: [
      "You can use the public calculators anonymously. You do not need to create an account, provide your name or provide an email address to use the calculator tools.",
      "Where practical, you may use iBudget without identifying yourself. Some technical information may still be processed automatically by the website, hosting provider, database provider or advertising services so that the site can function securely and reliably.",
    ],
  },
  {
    heading: "3. Information we collect",
    paragraphs: [
      "iBudget only aims to collect information that is reasonably necessary for operating and improving the website. Depending on how you use the site, the following information may be collected or processed:",
    ],
    bullets: [
      "Anonymous calculator usage data, such as calculator type and a locally stored session identifier used for basic calculator statistics.",
      "Saved calculation data, if you choose to save or share a calculation, including input data, result data, a share token and related expiry information.",
      "Technical server information, which may include IP address, browser type, device information, referring page, date and time of access, and error logs generated by hosting or security systems.",
      "Admin CMS information for site administrators only, such as login details handled through Supabase Auth and article content entered into the CMS.",
      "Advertising and cookie-related information when Google AdSense or other Google advertising services are enabled, including identifiers used to serve, measure and limit ads.",
      "Contact information in the future if iBudget adds an optional contact form, newsletter or support form. If that happens, this policy will be updated to explain the extra collection in more detail.",
    ],
  },
  {
    heading: "4. Calculation data and financial information",
    paragraphs: [
      "The calculators ask you to enter figures such as income, loan amount, deposit, interest rate, property price, state or territory, repayment assumptions and other calculator inputs. These figures are used to produce estimates.",
      "iBudget does not ask for sensitive personal information such as health information, tax file numbers, bank account credentials, identity documents or credit card details. Calculator inputs may relate to your financial circumstances, but iBudget does not use them to provide personal financial advice or assess your eligibility for a financial product.",
      "If you do not use the save or share function, calculator information is intended to be used in your browser for the calculator result. If you choose to save or share a calculation, the saved calculation data is stored in Supabase and is designed to expire after 30 days.",
    ],
  },
  {
    heading: "5. How we collect information",
    paragraphs: [
      "Information may be collected directly when you enter data into a calculator, save a calculation, use an admin CMS function, or contact iBudget if a contact option is added later.",
      "Information may also be collected indirectly through website technologies, local browser storage, cookies, Supabase, Vercel hosting, Google AdSense and ordinary server logs.",
    ],
  },
  {
    heading: "6. Why we collect and use information",
    paragraphs: [
      "iBudget uses information for practical website purposes, including:",
    ],
    bullets: [
      "providing calculator functionality and showing estimate results;",
      "allowing users to save and share calculations when they choose to use that feature;",
      "monitoring calculator usage in an anonymous or aggregated way so the site can be improved;",
      "operating the CMS and administering published resources;",
      "maintaining website security, diagnosing errors and preventing misuse;",
      "displaying and measuring ads through Google AdSense once advertising is enabled; and",
      "responding to privacy, technical or support enquiries if contact functionality is used.",
    ],
  },
  {
    heading: "7. Cookies, local storage and advertising",
    paragraphs: [
      "iBudget may use local storage or similar browser storage to keep a session identifier for anonymous calculator statistics and to support site functionality. This helps understand calculator usage without requiring a public user account.",
      "Google AdSense may use cookies, web beacons, IP addresses or other identifiers to serve ads, measure ad performance, prevent fraud and personalise or limit advertising where permitted. Google may process information according to its own policies and advertising technologies.",
      "You can control cookies through your browser settings. Blocking cookies or local storage may affect some functionality, including saved calculations, analytics or ad behaviour.",
    ],
  },
  {
    heading: "8. Storage, security and retention",
    paragraphs: [
      "iBudget uses Supabase for database and authentication services and Vercel for hosting. Reasonable steps are taken to protect information from misuse, interference, loss, unauthorised access, modification or disclosure.",
      "Saved calculations are designed to expire after 30 days. Some technical logs may be retained by service providers for operational, security, debugging or compliance purposes according to their own retention practices.",
      "No internet service can be guaranteed to be completely secure. You should avoid entering information that is unnecessarily identifying or sensitive into calculator fields.",
    ],
  },
  {
    heading: "9. Sharing information with third parties",
    paragraphs: [
      "iBudget does not sell personal information. Information may be shared with service providers where reasonably necessary to operate the website, including:",
    ],
    bullets: [
      "Supabase, for database, authentication and storage services;",
      "Vercel, for hosting, deployment, server logs and performance services;",
      "Google AdSense and related Google services, for advertising, measurement and fraud prevention once ads are enabled; and",
      "professional advisers, regulators or authorities if required by law, to protect legal rights, or to respond to a lawful request.",
    ],
  },
  {
    heading: "10. Overseas disclosure and hosting",
    paragraphs: [
      "Supabase, Vercel and Google operate globally. Information processed through these services may be stored, transferred or accessed outside Australia, including in countries where those providers or their infrastructure partners operate.",
      "Where practical, iBudget aims to use reputable service providers with security and privacy controls. By using the website, you understand that some website data may be processed outside Australia as part of normal cloud hosting, database, analytics and advertising operations.",
    ],
  },
  {
    heading: "11. Direct marketing",
    paragraphs: [
      "iBudget does not currently operate an email newsletter or direct marketing mailing list. If this changes, users will only be contacted where permitted and will be given a clear way to opt out.",
      "Google advertising may involve personalised or contextual ads depending on your settings, browser, region and Google’s advertising systems.",
    ],
  },
  {
    heading: "12. Accessing or correcting your information",
    paragraphs: [
      "You may request access to personal information that iBudget holds about you, or ask for correction if you believe it is inaccurate, out of date, incomplete, irrelevant or misleading.",
      "Because most public calculator use is anonymous, iBudget may not be able to identify data that relates to you unless you provide enough information to locate it, such as a saved calculation share token or details of a privacy request.",
      "Privacy requests can be sent to: privacy@ibudget.au.",
    ],
  },
  {
    heading: "13. Privacy complaints",
    paragraphs: [
      "If you believe iBudget has mishandled your privacy, please contact privacy@ibudget.au with the details of your concern. iBudget will aim to acknowledge and review privacy complaints within a reasonable time.",
      "If you are not satisfied with the response, you may contact the Office of the Australian Information Commissioner (OAIC) for further information about making a privacy complaint.",
    ],
  },
  {
    heading: "14. Changes to this policy",
    paragraphs: [
      "iBudget may update this Privacy Policy as the site changes, including if new features such as newsletters, public user accounts, additional analytics or extra advertising tools are added. The updated version will be published on this page with a revised effective date.",
    ],
  },
  {
    heading: "15. Contact",
    paragraphs: [
      "For privacy questions, access or correction requests, or privacy complaints, contact: privacy@ibudget.au.",
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      effectiveDate="4 May 2026"
      description="This policy explains how iBudget.au handles information when you use the calculators, save calculations, read resources, interact with advertising or use the admin CMS."
      sections={sections}
    />
  );
}
